### ISSUE TITLE
Sort the sample data by date with command line not working.

### ISSUE THREAD

**Issue by YanLiang1102** [oudalab/co-incidents#8]

**Comment by YanLiang1102** [comment]
time sort -t$'\t' -k 14 sampleEventData.tsv >sorted-sampleEventData.tsv

**Comment by YanLiang1102** [comment]
@cegme  Dr. Grant any idea I am trying to sort against the date8 like "20150801" but it looks like not working?

**Comment by cegme** [comment]
You probably want to sort numerically. Add the `-n` flag to the sort.

**Comment by YanLiang1102** [comment]
@cegme I tried not working ,well numerially or alphabeticallly should be the same result, based on the format I have.

**Comment by cegme** [comment]
Can you give an example of the sampleEventData.tsv?

**Comment by YanLiang1102** [comment]
@cegme  I put the sample csv on hanover under your directory

**Comment by YanLiang1102** [comment]
This is not working because I only have one line in the tsv, .[]|[] in jq will give u multiple line when transfer it to csv #7  code is in issue 7
